# Generated by Django 3.2.5 on 2024-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Укажите название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('image', models.URLField(verbose_name='Вставте фото фильма')),
                ('category', models.CharField(choices=[('Ужасы', 'Ужасы'), ('Комедия', 'Комедия'), ('Детектив', 'Детектив'), ('Боевик', 'Боевик'), ('Исторические', 'Исторические')], max_length=100, verbose_name='Выберите котигорию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
