# Generated by Django 3.2.5 on 2024-01-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0005_alter_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='TVShow',
            new_name='tv_show',
        ),
    ]
