# Generated by Django 3.2.5 on 2024-01-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persongame',
            options={'verbose_name': 'Персонажа'},
        ),
        migrations.RemoveField(
            model_name='persongame',
            name='stort',
        ),
        migrations.AddField(
            model_name='persongame',
            name='sport',
            field=models.CharField(choices=[('Карате', 'Карате'), ('Кунг-фу', 'Кунг-фу'), ('Бокс', 'Бокс'), ('Рестлинг', 'Рестлинг'), ('Ниндзютсу', 'Ниндзютсу')], max_length=100, null=True, verbose_name='Выберите стиль персонажа'),
        ),
        migrations.AlterField(
            model_name='persongame',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Укажите имя персонажа'),
        ),
    ]
